-
  branches:
    only:
      - master

  configuration: Release

  install:
    - ps: Start-FileDownload 'http://neo4j.com/artifact.php?name=neo4j-community-2.1.5-windows.zip' -FileName 'c:\projects\CypherNetCore\neo4j-community-2.1.5-windows.zip'
    - cmd: 7z x c:\projects\CypherNetCore\neo4j-community-2.1.5-windows.zip
    - cmd: c:\projects\CypherNetCore\neo4j-community-2.1.5\bin\Neo4jInstaller.bat install
    - ps: .\src\.nuget\nuget.exe restore .\src\CypherNet.Core.sln

  assembly_info:
    patch: true
  
  build:
    publish_nuget: true

  deploy:
    provider: NuGet
    api_key:
      secure: 8imu4ltmARd9TSapCxG53y7ysUZYyFS1SJPqvEMJjm4uYFZmQhGPto8AWRqDoweh
    skip_symbols: true
    artifact: /.*\.nupkg/
  
-
  # "fall back" configuration for all other branches
  install:
    - ps: Start-FileDownload 'http://neo4j.com/artifact.php?name=neo4j-community-2.1.5-windows.zip' -FileName 'c:\projects\CypherNetCore\neo4j-community-2.1.5-windows.zip'
    - cmd: 7z x c:\projects\CypherNetCore\neo4j-community-2.1.5-windows.zip
    - cmd: c:\projects\CypherNetCore\neo4j-community-2.1.5\bin\Neo4jInstaller.bat install
    - ps: .\src\.nuget\nuget.exe restore .\src\CypherNet.Core.sln
