install:
  - ps: Start-FileDownload 'http://neo4j.com/artifact.php?name=neo4j-community-2.1.5-windows.zip' -FileName 'c:\projects\CypherNetCore\neo4j-community-2.1.5-windows.zip'
  - cmd: 7z x c:\projects\CypherNetCore\neo4j-community-2.1.5-windows.zip
  - cmd: c:\projects\CypherNetCore\neo4j-community-2.1.5\bin\Neo4jInstaller.bat install
  - ps: .\src\.nuget\nuget.exe restore .\src\CypherNet.Core.sln

assembly_info:
  patch: true
  
build:
  publish_nuget: true
